server:
  port: ${SERVER_PORT:8080}

gateway:
  routes:
    customer-service-url: ${GATEWAY_ROUTES_CUSTOMER_SERVICE_URL:http://localhost:8081}
    account-service-url: ${GATEWAY_ROUTES_ACCOUNT_SERVICE_URL:http://localhost:8082}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
