services:
  postgres:
    image: postgres:17
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - bank_postgres_data:/var/lib/postgresql/data

volumes:
  bank_postgres_data: