server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankdb}
    username: ${SPRING_DATASOURCE_USERNAME:bankuser}
    password: ${SPRING_DATASOURCE_PASSWORD:bankpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: account_service
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    default-schema: account_service
    schemas: account_service
    table: flyway_schema_history_account

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
