apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          image: document-service:local
          ports:
            - containerPort: 8087
          env:
            - name: SERVER_PORT
              value: "8087"
